"""Add pause/resume and task employee assignment

Revision ID: 8bbf33004827
Revises: f52075db60fc
Create Date: 2025-11-25 14:19:06.572537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bbf33004827'
down_revision = 'f52075db60fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_allowed_employees',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'employee_id')
    )
    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pause_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_paused_duration', sa.Integer(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_all', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('assigned_to_all')

    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.drop_column('total_paused_duration')
        batch_op.drop_column('pause_time')

    op.drop_table('task_allowed_employees')
    # ### end Alembic commands ###
